import {erpFormatAmount,erpParseAmount,erpScale} from './design-erp-money.js';
export const erpCatalog=[
 {id:'erp-ledger',name:'ERP 전표 조회 테이블',description:'회사·상태·통화 필터, 정렬·행 선택·통화별 합계'},
 {id:'erp-journal',name:'ERP 전표 입력 그리드',description:'셀 편집·엑셀 붙여넣기·차대변 검증·초안 전달'}
].map(item=>({...item,group:'ERP 회계',platform:'erp-web'}));
const entries=[
 ['l1','1000','190000001','2026-09-01','600100','사무용품','CC100','KRW','110000','','posted'],
 ['l2','1000','190000001','2026-09-01','210100','미지급금','CC100','KRW','','110000','posted'],
 ['l3','1000','190000002','2026-09-03','610200','소프트웨어','IT100','USD','1250.50','','draft'],
 ['l4','1000','190000002','2026-09-03','210100','미지급금','IT100','USD','','1250.50','draft'],
 ['l5','2000','190000003','2026-09-05','620100','출장비','CC200','KRW','50000','','held'],
 ['l6','2000','190000003','2026-09-05','110100','보통예금','CC200','KRW','','50000','held']
];
const statusNames={posted:'전기 완료',draft:'초안',held:'보류'};
const ledgerRows=entries.map(([id,company,document,date,account,description,cost,currency,debit,credit,status])=>`<tr data-erp-row data-row-id="${id}" data-company="${company}" data-document="${document}" data-date="${date}" data-account="${account}" data-currency="${currency}" data-status="${status}" data-debit="${debit}" data-credit="${credit}"><td><input type="checkbox" data-erp-select aria-label="${document} ${account} 선택"></td><th scope="row">${document}</th><td>${company}</td><td>2026</td><td>${date}</td><td>${account}</td><td>${description}</td><td>${cost}</td><td>${currency}</td><td class="oc-erp-money">${erpFormatAmount(erpParseAmount(debit,erpScale(currency)),erpScale(currency))}</td><td class="oc-erp-money">${erpFormatAmount(erpParseAmount(credit,erpScale(currency)),erpScale(currency))}</td><td><span class="oc-erp-badge">${statusNames[status]}</span></td></tr>`).join('');
const fieldNames=['계정','적요','원가센터','차변','대변'];
const journalRow=index=>`<tr data-journal-row data-line-id="line-${index}"><th scope="row" data-line-number>${index}</th>${['account','description','costCenter','debit','credit'].map((field,i)=>`<td><input data-erp-cell="${field}" aria-label="${index}행 ${fieldNames[i]}" autocomplete="off" maxlength="${i===1?100:i>=3?30:10}"${i>=3?' inputmode="decimal"':''}></td>`).join('')}<td><button type="button" data-erp-remove aria-label="${index}행 삭제">삭제</button></td><td class="oc-erp-error" data-line-error></td></tr>`;
const currencies='<option value="KRW">KRW · 원</option><option value="USD">USD · 달러</option><option value="EUR">EUR · 유로</option><option value="JPY">JPY · 엔</option>';
export const erpMarkup={
 'erp-ledger':`<div class="oc-erp-body" data-erp-ledger><header class="oc-erp-heading"><div><p class="oc-erp-eyebrow">FINANCE / JOURNAL ITEMS</p><h2>전표 항목 조회</h2><p class="oc-muted">회사와 통화를 구분해 분개 항목을 검토하세요.</p></div><span class="oc-erp-badge">로컬 예시</span></header><div class="oc-erp-filters"><div><label for="__id__-query">전표·계정·적요 검색</label><input id="__id__-query" type="search" data-erp-query autocomplete="off"></div><div><label for="__id__-company">회사 코드</label><select id="__id__-company" data-erp-company-filter><option value="all">전체 회사</option><option value="1000">1000</option><option value="2000">2000</option></select></div><div><label for="__id__-currency">통화</label><select id="__id__-currency" data-erp-currency-filter><option value="all">전체 통화</option>${currencies}</select></div><div><label for="__id__-status">전표 상태</label><select id="__id__-status" data-erp-status-filter><option value="all">전체 상태</option><option value="posted">전기 완료</option><option value="draft">초안</option><option value="held">보류</option></select></div><button type="button" data-erp-reset>필터 초기화</button></div><div class="oc-erp-scroll" role="region" aria-label="전표 항목 표" tabindex="0"><table><caption>샘플 분개 항목 · 표시 행 합계는 회사·통화별로 구분됩니다.</caption><thead><tr><th scope="col"><input type="checkbox" data-erp-select-all aria-label="표시 행 전체 선택"></th><th scope="col" aria-sort="none"><button type="button" data-erp-sort="document">전표 번호 ↕</button></th><th scope="col">회사</th><th scope="col">회계연도</th><th scope="col" aria-sort="none"><button type="button" data-erp-sort="date">전기일 ↕</button></th><th scope="col" aria-sort="none"><button type="button" data-erp-sort="account">계정 ↕</button></th><th scope="col">적요</th><th scope="col">원가센터</th><th scope="col">통화</th><th scope="col" class="oc-erp-money">차변</th><th scope="col" class="oc-erp-money">대변</th><th scope="col">상태</th></tr></thead><tbody>${ledgerRows}</tbody></table></div><p data-erp-empty hidden>조건에 맞는 전표 항목이 없습니다.</p><div class="oc-erp-totals" data-erp-totals><p>1000 · KRW · 차변 110,000 · 대변 110,000 · 차이 0</p><p>1000 · USD · 차변 1,250.50 · 대변 1,250.50 · 차이 0.00</p><p>2000 · KRW · 차변 50,000 · 대변 50,000 · 차이 0</p></div><div class="oc-erp-footer"><p role="status" data-erp-status>표시 6행 · 선택 0행</p><button type="button" data-erp-review disabled>선택 행 검토</button></div><p class="oc-muted">필터를 바꾸면 선택이 해제됩니다. 조회 합계는 표시 행 기준이며 전표 전체의 검증 결과가 아닙니다.</p></div>`,
 'erp-journal':`<div class="oc-erp-body" data-erp-journal data-next-line="4"><header class="oc-erp-heading"><div><p class="oc-erp-eyebrow">FINANCE / JOURNAL DRAFT</p><h2>전표 입력 그리드</h2><p class="oc-muted">한 전표의 차변·대변을 입력하고 초안을 검증하세요.</p></div><span class="oc-erp-badge">로컬 초안</span></header><div class="oc-erp-filters"><div><label for="__id__-company">회사 코드</label><input id="__id__-company" data-journal-company placeholder="예: 1000" maxlength="4" autocomplete="off"></div><div><label for="__id__-date">전기일</label><input id="__id__-date" data-journal-date type="date"></div><div><label for="__id__-currency">전표 통화</label><select id="__id__-currency" data-journal-currency>${currencies}</select></div></div><p class="oc-muted">통화는 금액 입력 전에 선택하세요. KRW·JPY는 정수, USD·EUR는 소수 2자리까지 지원합니다.</p><div class="oc-erp-toolbar"><button type="button" data-erp-add>행 추가</button><span class="oc-muted">Tab 셀 이동 · Enter 다음 행 · Alt+방향키 · 엑셀 셀 붙여넣기</span></div><div class="oc-erp-scroll" role="region" aria-label="전표 입력 그리드" tabindex="0"><table><caption>계정 · 적요 · 원가센터 · 차변 · 대변 순서로 붙여넣으세요. 최대 200행.</caption><thead><tr><th scope="col">행</th><th scope="col">계정</th><th scope="col">적요</th><th scope="col">원가센터</th><th scope="col">차변</th><th scope="col">대변</th><th scope="col">작업</th><th scope="col">검증</th></tr></thead><tbody>${[1,2,3].map(journalRow).join('')}</tbody></table></div><div class="oc-erp-summary"><div><span>차변 합계</span><strong data-journal-debit>0 KRW</strong></div><div><span>대변 합계</span><strong data-journal-credit>0 KRW</strong></div><div><span>차이</span><strong data-journal-difference>0 KRW</strong></div></div><p role="status" data-journal-validation>회사 코드·전기일과 2개 이상의 분개를 입력하세요.</p><div class="oc-erp-footer"><button type="button" data-erp-validate>초안 검증</button><button type="button" data-erp-draft disabled>검증된 초안 전달</button></div><p role="status" data-erp-status></p><p class="oc-muted">실제 전기·저장·환산은 수행하지 않습니다. SAP 계정·기간·권한 검증은 연결한 서버에서 처리하세요.</p></div>`
};
export const erpStyles=`
.oc-design[data-erp=true]{padding:0;container-type:inline-size;overflow-wrap:anywhere}.oc-design .oc-erp-body{padding:24px;min-width:0}.oc-design .oc-erp-heading{display:flex;align-items:start;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:24px}.oc-design .oc-erp-eyebrow{font-size:11px;letter-spacing:.1em;color:var(--oc-muted)}.oc-design .oc-erp-heading h2{margin-bottom:8px}.oc-design .oc-erp-badge{display:inline-block;padding:4px 10px;border:1px solid var(--oc-border);border-radius:6px;font-size:12px;white-space:nowrap;background:var(--oc-background)}
.oc-design .oc-erp-filters{display:flex;flex-wrap:wrap;align-items:end;gap:12px;margin-bottom:18px}.oc-design .oc-erp-filters>div{display:grid;gap:6px;flex:1;min-width:150px}.oc-design[data-erp=true] select{font:inherit;min-height:44px;width:100%;padding:10px;border:1px solid var(--oc-border);border-radius:8px;background:var(--oc-background);color:var(--oc-text)}.oc-design[data-erp=true] input{min-height:44px}.oc-design[data-erp=true] input[type=checkbox]{min-height:20px;width:20px;cursor:pointer}.oc-design[data-erp=true] button{min-height:44px}.oc-design .oc-erp-toolbar,.oc-design .oc-erp-footer{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px;margin:16px 0}.oc-design .oc-erp-toolbar span{font-size:12px}.oc-design .oc-erp-scroll{overflow:auto;max-width:100%;max-height:440px;overscroll-behavior:contain;border:1px solid var(--oc-border);border-radius:8px}.oc-design .oc-erp-scroll table{min-width:1080px;border-collapse:separate;border-spacing:0;font-size:13px}.oc-design .oc-erp-scroll caption{padding:12px;background:var(--oc-background);font-size:12px}.oc-design .oc-erp-scroll th,.oc-design .oc-erp-scroll td{padding:10px;background:var(--oc-surface)}.oc-design .oc-erp-scroll thead th{position:sticky;top:0;z-index:2;background:var(--oc-background)}.oc-design .oc-erp-scroll tbody th{position:sticky;left:0;z-index:1;background:var(--oc-background)}.oc-design .oc-erp-scroll thead button{font:inherit;padding:4px 8px;background:transparent;color:var(--oc-text);white-space:nowrap}.oc-design .oc-erp-money{text-align:right;font-variant-numeric:tabular-nums}.oc-design .oc-erp-scroll [data-selected] td{background:color-mix(in srgb,var(--oc-accent) 8%,var(--oc-surface))}.oc-design .oc-erp-totals{padding:12px 16px;margin-top:16px;background:var(--oc-background);border:1px solid var(--oc-border);border-radius:8px;font-variant-numeric:tabular-nums;font-size:13px}.oc-design .oc-erp-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:20px}.oc-design .oc-erp-summary>div{display:grid;gap:6px;padding:16px;background:var(--oc-background);border-radius:8px;min-width:0}.oc-design .oc-erp-summary span{font-size:12px;color:var(--oc-muted)}.oc-design .oc-erp-summary strong{font-size:20px;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.oc-design [data-erp-cell]{min-width:120px}.oc-design [data-erp-cell=description]{min-width:170px}.oc-design [data-erp-cell=debit],.oc-design [data-erp-cell=credit]{text-align:right;font-variant-numeric:tabular-nums;min-width:150px}.oc-design .oc-erp-error{color:var(--oc-danger);min-width:200px;white-space:normal}.oc-design [data-journal-row][data-invalid] input{border-color:var(--oc-danger)}.oc-design [data-journal-validation][data-valid=true]{color:var(--oc-accent)}.oc-design [data-journal-validation][data-valid=false]{color:var(--oc-danger)}
.oc-design [data-erp-ledger] thead th:nth-child(2),.oc-design [data-erp-journal] thead th:first-child{left:0;z-index:3}
@container(max-width:560px){.oc-design .oc-erp-body{padding:16px}.oc-design .oc-erp-summary{grid-template-columns:1fr}.oc-design .oc-erp-filters>div{flex-basis:100%}}
`;
