export const adminCatalog = [
  {id:'admin-layout',name:'관리자 레이아웃',description:'접을 수 있는 사이드바·메뉴 선택'},
  {id:'admin-dashboard',name:'관리자 대시보드',description:'기간별 통계 카드·실적 막대'},
  {id:'admin-table',name:'관리자 데이터 테이블',description:'검색·정렬·행 선택·사용자 상세 패널'},
  {id:'admin-user-form',name:'사용자 초대 폼',description:'이름·이메일 검증·역할 안내'},
  {id:'admin-activity',name:'관리자 활동 로그',description:'활동 검색·유형 필터·빈 결과'}
].map(item=>({...item,group:'관리자',platform:'admin-web'}));

const sampleRows = [
  ['u01','김민지','minji@example.com','활성','active','운영팀'],
  ['u02','박서준','seojun@example.com','대기','pending','디자인팀'],
  ['u03','이서연','seoyeon@example.com','활성','active','개발팀'],
  ['u04','정도윤','doyun@example.com','중지','paused','운영팀'],
  ['u05','최지우','jiwoo@example.com','활성','active','디자인팀'],
  ['u06','한유진','yujin@example.com','대기','pending','개발팀'],
  ['u07','강하준','hajun@example.com','활성','active','운영팀'],
  ['u08','윤수아','sua@example.com','중지','paused','개발팀']
];
const tableRows = sampleRows.map(([id,name,email,status,key,team],index)=>`<tr data-admin-row data-row-id="${id}" data-status="${key}" data-order="${index}"${index>2?' hidden':''}><td><label class="oc-admin-check"><input type="checkbox" data-row-select aria-label="${name} 선택"></label></td><th scope="row" data-name><button type="button" class="oc-admin-person" data-admin-detail aria-haspopup="dialog" aria-label="${name} 상세 보기">${name}</button><small>${email}</small></th><td data-team>${team}</td><td><span class="oc-admin-badge" data-status="${key}">${status}</span></td></tr>`).join('');
const detailPanel = `<dialog class="oc-admin-detail" aria-labelledby="__id__-detail-title"><header><h2 id="__id__-detail-title">사용자 상세</h2><button type="button" data-admin-detail-close aria-label="사용자 상세 닫기">닫기</button></header><dl><dt>이름</dt><dd data-detail-name></dd><dt>이메일</dt><dd data-detail-email></dd><dt>팀</dt><dd data-detail-team></dd><dt>상태</dt><dd data-detail-status></dd></dl><p class="oc-muted">예시 사용자 정보입니다.</p></dialog>`;
const search = (id,label,attr) => `<label class="oc-admin-field" for="__id__-${id}">${label}<input id="__id__-${id}" type="search" ${attr} placeholder="이름이나 내용 검색" autocomplete="off"></label>`;
const heading = (eyebrow,title,description) => `<header class="oc-admin-heading"><div><p class="oc-admin-eyebrow">${eyebrow}</p><h2>${title}</h2><p class="oc-muted">${description}</p></div><span class="oc-admin-badge">예시 데이터</span></header>`;
export const adminMarkup = {
  'admin-layout': `<div class="oc-admin-shell"><header class="oc-admin-top"><strong>Workspace / Admin</strong><button type="button" data-admin-menu aria-expanded="true" aria-controls="__id__-navigation">메뉴 접기</button></header><div class="oc-admin-layout"><nav id="__id__-navigation" class="oc-admin-nav" aria-label="관리자 메뉴"><span class="oc-admin-eyebrow">WORKSPACE</span><button type="button" data-admin-nav="overview" aria-current="page">개요</button><button type="button" data-admin-nav="members">사용자</button><button type="button" data-admin-nav="settings">설정</button></nav><div class="oc-admin-body"><p class="oc-admin-eyebrow">YOUR WORKSPACE</p><h2 data-admin-section>개요</h2><p data-admin-section-description>오늘의 업무와 최근 활동을 확인하세요.</p><div class="oc-admin-card"><strong>팀의 작업을 한곳에서</strong><p class="oc-muted">프로젝트에 필요한 컴포넌트를 이 영역에 배치하세요.</p></div><p role="status" data-admin-navigation-status></p></div></div></div>`,
  'admin-dashboard': `<div class="oc-admin-body">${heading('WORKSPACE OVERVIEW','운영 현황','핵심 지표와 목표 달성률을 확인하세요.')}<div class="oc-admin-field"><label for="__id__-period">조회 기간</label><select id="__id__-period" data-admin-period><option value="week">최근 7일</option><option value="month">최근 30일</option></select></div><div class="oc-admin-metrics"><article class="oc-admin-card"><h3>신규 가입</h3><strong class="oc-admin-number" data-week="248" data-month="1,048">248</strong><p class="oc-muted">신규 사용자</p></article><article class="oc-admin-card"><h3>주문</h3><strong class="oc-admin-number" data-week="128" data-month="642">128</strong><p class="oc-muted">접수된 주문</p></article><article class="oc-admin-card"><h3>문의</h3><strong class="oc-admin-number" data-week="12" data-month="38">12</strong><p class="oc-muted">접수된 문의</p></article></div><section class="oc-admin-card"><h3>목표 달성률</h3><div class="oc-admin-goals"><label for="__id__-goal-signups">신규 가입</label><meter id="__id__-goal-signups" min="0" max="100" value="62" data-week="62" data-month="84">62%</meter><label for="__id__-goal-orders">주문</label><meter id="__id__-goal-orders" min="0" max="100" value="48" data-week="48" data-month="76">48%</meter><label for="__id__-goal-replies">문의 응답</label><meter id="__id__-goal-replies" min="0" max="100" value="90" data-week="90" data-month="95">90%</meter></div></section><p role="status" data-admin-period-status>최근 7일 예시 데이터</p></div>`,
  'admin-table': `<div class="oc-admin-body" data-admin-table>${heading('MEMBER DIRECTORY','사용자 목록','검색하고 필요한 사용자를 선택하세요.')}<div class="oc-admin-filters">${search('members-search','사용자 검색','data-admin-query')}<div class="oc-admin-field"><label for="__id__-members-status">상태</label><select id="__id__-members-status" data-admin-filter><option value="all">전체 상태</option><option value="active">활성</option><option value="pending">대기</option><option value="paused">중지</option></select></div><button type="button" data-admin-reset>필터 초기화</button></div><div class="oc-admin-table-scroll" role="region" aria-label="사용자 목록 표" tabindex="0"><table><caption>사용자 디렉터리 · 예시 8명</caption><thead><tr><th scope="col"><label class="oc-admin-check"><input type="checkbox" data-select-page aria-label="현재 페이지 전체 선택"></label></th><th scope="col" aria-sort="none"><button type="button" data-admin-sort>이름 정렬 ↕</button></th><th scope="col">팀</th><th scope="col">상태</th></tr></thead><tbody>${tableRows}</tbody></table></div><p data-admin-empty hidden>조건에 맞는 사용자가 없습니다.</p><div class="oc-admin-table-footer"><p role="status" data-admin-table-status>선택 0개 · 8개 중 1–3 · 1/3 페이지</p><div class="oc-admin-pagination" role="group" aria-label="페이지 이동"><button type="button" data-admin-page="-1" disabled>이전</button><button type="button" data-admin-page="1">다음</button></div><button type="button" data-admin-bulk disabled>선택 항목 검토</button></div><p role="status" data-admin-bulk-status></p>${detailPanel}</div>`,
  'admin-user-form': `<div class="oc-admin-body">${heading('TEAM ACCESS','사용자 초대','팀에 합류할 사람과 역할을 지정하세요.')}<form><label for="__id__-invite-name">이름</label><input id="__id__-invite-name" name="name" required autocomplete="name"><label for="__id__-invite-email">이메일</label><input id="__id__-invite-email" name="email" type="email" required autocomplete="email"><label for="__id__-invite-role">역할</label><select id="__id__-invite-role" name="role" data-admin-role aria-describedby="__id__-role-note"><option value="viewer">조회자</option><option value="editor">편집자</option><option value="admin">관리자</option></select><p id="__id__-role-note" class="oc-admin-card" data-admin-role-note role="status">조회자: 목록과 상세 화면을 조회합니다.</p><p class="oc-muted">초대 전 역할과 이메일을 확인하세요.</p><button type="submit">초대 요청</button><p role="status" data-feedback></p></form></div>`,
  'admin-activity': `<div class="oc-admin-body">${heading('ACTIVITY LOG','최근 활동','사용자와 시스템의 작업 내역을 확인하세요.')}<div class="oc-admin-filters">${search('activity-search','활동 검색','data-admin-log-query')}<div class="oc-admin-field"><label for="__id__-activity-kind">활동 유형</label><select id="__id__-activity-kind" data-admin-log-filter><option value="all">전체 유형</option><option value="member">사용자</option><option value="project">프로젝트</option><option value="system">시스템</option></select></div></div><ol class="oc-admin-timeline"><li data-admin-log="member"><span class="oc-admin-badge">사용자</span><div><strong>김민지 님이 팀에 참여했습니다.</strong><p class="oc-muted">운영팀 · 초대 수락</p></div><time datetime="2026-09-01T09:40:00+09:00">09:40</time></li><li data-admin-log="project"><span class="oc-admin-badge">프로젝트</span><div><strong>디자인 시스템을 업데이트했습니다.</strong><p class="oc-muted">박서준 · 컴포넌트 검토</p></div><time datetime="2026-09-01T09:20:00+09:00">09:20</time></li><li data-admin-log="system"><span class="oc-admin-badge">시스템</span><div><strong>정기 백업을 완료했습니다.</strong><p class="oc-muted">자동 작업 · 예시 기록</p></div><time datetime="2026-09-01T09:00:00+09:00">09:00</time></li></ol><p role="status" data-admin-log-count>3개 활동</p><p data-admin-log-empty hidden>조건에 맞는 활동이 없습니다.</p></div>`
};

export const adminStyles = `
.oc-design[data-admin=true]{padding:0;container-type:inline-size;overflow-wrap:anywhere}
.oc-design .oc-admin-body{padding:24px;min-width:0}.oc-design .oc-admin-eyebrow{font-size:11px;letter-spacing:.08em;color:var(--oc-muted)}
.oc-design .oc-admin-heading{display:flex;justify-content:space-between;align-items:start;flex-wrap:wrap;gap:12px;margin-bottom:24px}.oc-design .oc-admin-heading h2{margin-bottom:8px}.oc-design .oc-admin-heading p{margin:4px 0}
.oc-design .oc-admin-badge{display:inline-block;padding:4px 10px;border:1px solid var(--oc-border);border-radius:99px;font-size:12px;white-space:nowrap;background:var(--oc-background);color:var(--oc-text)}.oc-design .oc-admin-badge[data-status=active]{border-color:var(--oc-accent);color:var(--oc-accent)}
.oc-design .oc-admin-card{padding:20px;border:1px solid var(--oc-border);border-radius:var(--oc-radius);background:var(--oc-background);min-width:0}.oc-design .oc-admin-card h3{margin:0 0 12px;font-size:14px}
.oc-design .oc-admin-field{display:grid;gap:6px;min-width:0}.oc-design[data-admin=true] select{font:inherit;min-height:44px;max-width:100%;padding:10px;border:1px solid var(--oc-border);border-radius:8px;background:var(--oc-background);color:var(--oc-text)}
.oc-design .oc-admin-filters{display:flex;align-items:end;flex-wrap:wrap;gap:12px;margin-bottom:20px}.oc-design .oc-admin-filters .oc-admin-field:first-child{flex:1;min-width:150px}
.oc-design .oc-admin-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin:20px 0}.oc-design .oc-admin-number{font-size:30px;letter-spacing:-.04em}.oc-design .oc-admin-goals{display:grid;grid-template-columns:auto minmax(0,1fr);gap:12px;align-items:center}.oc-design .oc-admin-goals meter{width:100%;height:24px;accent-color:var(--oc-accent)}
.oc-design .oc-admin-top{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:12px;padding:16px 20px;border-bottom:1px solid var(--oc-border)}.oc-design .oc-admin-top button{background:var(--oc-background);color:var(--oc-text);border-color:var(--oc-border)}
.oc-design .oc-admin-layout{display:grid;grid-template-columns:170px minmax(0,1fr);min-height:320px}.oc-design .oc-admin-layout:has(>.oc-admin-nav[hidden]){grid-template-columns:minmax(0,1fr)}.oc-design .oc-admin-nav{display:flex;flex-direction:column;gap:8px;padding:20px 12px;border-right:1px solid var(--oc-border);background:var(--oc-background)}.oc-design .oc-admin-nav button{text-align:left}.oc-design .oc-admin-nav button:not([aria-current]){background:transparent;color:var(--oc-muted)}
.oc-design .oc-admin-table-scroll{overflow:auto;max-width:100%}.oc-design .oc-admin-table-scroll table{min-width:520px}.oc-design .oc-admin-table-scroll caption{font-size:12px;color:var(--oc-muted)}.oc-design .oc-admin-table-scroll small{display:block;font-weight:400;color:var(--oc-muted)}.oc-design .oc-admin-table-scroll th button{padding:6px 10px;background:var(--oc-background);color:var(--oc-text);border-color:var(--oc-border)}
.oc-design .oc-admin-check{display:grid;place-items:center;min-width:44px;min-height:44px;cursor:pointer}.oc-design .oc-admin-check input{margin:0}.oc-design .oc-admin-table-footer{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-top:16px}.oc-design .oc-admin-table-footer p{flex:1;font-size:12px;min-width:180px}.oc-design .oc-admin-pagination{display:flex;gap:8px}.oc-design .oc-admin-pagination button{background:var(--oc-background);color:var(--oc-text);border-color:var(--oc-border)}
.oc-design .oc-admin-timeline{list-style:none;padding:0}.oc-design .oc-admin-timeline li{display:flex;align-items:start;gap:14px;padding:18px 0;border-bottom:1px solid var(--oc-border)}.oc-design .oc-admin-timeline li>div{flex:1;min-width:0}.oc-design .oc-admin-timeline time{font-size:12px;color:var(--oc-muted)}
.oc-design [data-admin-row][data-selected]{background:color-mix(in srgb,var(--oc-accent) 10%,var(--oc-surface))}
.oc-design .oc-admin-table-scroll th .oc-admin-person{padding:4px 0;background:transparent;border-color:transparent;color:var(--oc-accent);text-decoration:underline;text-underline-offset:3px;min-height:44px}
.oc-design dialog.oc-admin-detail{position:fixed;inset:0 0 0 auto;margin:0;width:min(420px,100%);max-width:100%;height:100dvh;max-height:100dvh;overflow-y:auto;overscroll-behavior:contain;border:0;border-left:1px solid var(--oc-border);border-radius:20px 0 0 20px;padding:24px;box-shadow:-12px 0 40px #0002}
.oc-design .oc-admin-detail header{display:flex;align-items:start;justify-content:space-between;gap:12px;flex-wrap:wrap}.oc-design .oc-admin-detail h2{margin:8px 0}.oc-design .oc-admin-detail dt{font-size:12px;color:var(--oc-muted);margin-top:24px}.oc-design .oc-admin-detail dd{margin:6px 0;overflow-wrap:anywhere}
@container(max-width:520px){.oc-design .oc-admin-body{padding:16px}.oc-design .oc-admin-metrics{grid-template-columns:1fr}.oc-design .oc-admin-layout{grid-template-columns:1fr}.oc-design .oc-admin-nav{flex-direction:row;flex-wrap:wrap;border-right:0;border-bottom:1px solid var(--oc-border)}.oc-design .oc-admin-nav>span{width:100%}.oc-design .oc-admin-timeline li{flex-wrap:wrap}.oc-design .oc-admin-timeline li>div{flex-basis:65%}}
`;
