export const mobileCatalog = [
  {id:'mobile-tabs', name:'모바일 하단 탭바', description:'하단 화면 전환·방향키·안전 영역'},
  {id:'bottom-sheet', name:'바텀시트', description:'하단 액션 선택·닫기·포커스 복귀'},
  {id:'mobile-form', name:'모바일 입력 폼', description:'이름·이메일·연락처와 터치 입력'},
  {id:'sticky-action', name:'하단 고정 액션', description:'컨테이너 하단의 주문·예약 버튼'},
  {id:'mobile-list', name:'모바일 카드 목록', description:'카드 선택·로딩 스켈레톤'}
].map(item => ({...item, group:'모바일', platform:'mobile-web'}));

const mobileInput = (label, name, type, autocomplete, inputmode, hint) => `<label for="__id__-${name}">${label}</label><input id="__id__-${name}" name="${name}" type="${type}" autocomplete="${autocomplete}" inputmode="${inputmode}" enterkeyhint="${hint}" required>`;
export const mobileMarkup = {
  'mobile-tabs': `<div class="oc-mobile-screen"><div class="oc-mobile-content"><p class="oc-muted">MY WORKSPACE</p><div role="tabpanel" id="__id__-panel-0" aria-labelledby="__id__-tab-0" tabindex="0"><h2>오늘의 프로젝트</h2><p>작은 아이디어를 다음 화면으로.</p><div class="oc-mobile-card"><strong>디자인 시스템</strong><p>팀과 함께 일관된 화면을 만드세요.</p></div></div><div role="tabpanel" id="__id__-panel-1" aria-labelledby="__id__-tab-1" tabindex="0" hidden><h2>저장한 항목</h2><p>아직 저장한 프로젝트가 없습니다.</p></div><div role="tabpanel" id="__id__-panel-2" aria-labelledby="__id__-tab-2" tabindex="0" hidden><h2>내 계정</h2><p>프로필과 알림을 관리하세요.</p></div></div><div class="oc-mobile-tabs" role="tablist" aria-label="모바일 화면"><button type="button" role="tab" id="__id__-tab-0" aria-controls="__id__-panel-0" aria-selected="true" tabindex="0"><span aria-hidden="true">⌂</span>홈</button><button type="button" role="tab" id="__id__-tab-1" aria-controls="__id__-panel-1" aria-selected="false" tabindex="-1"><span aria-hidden="true">☆</span>저장</button><button type="button" role="tab" id="__id__-tab-2" aria-controls="__id__-panel-2" aria-selected="false" tabindex="-1"><span aria-hidden="true">○</span>내 계정</button></div></div>`,
  'bottom-sheet': `<div class="oc-mobile-screen"><div class="oc-mobile-content"><p class="oc-muted">QUICK ACTIONS</p><h2>필요한 작업을 한곳에서</h2><p>버튼을 눌러 하단 시트를 열어보세요.</p><button type="button" data-action="open-dialog">작업 선택</button><p role="status" data-sheet-result></p></div><dialog class="oc-sheet" aria-labelledby="__id__-sheet-title" aria-describedby="__id__-sheet-description"><span class="oc-sheet-handle" aria-hidden="true"></span><h2 id="__id__-sheet-title">어떤 작업을 할까요?</h2><p id="__id__-sheet-description">선택한 작업은 앱의 이벤트로 전달됩니다.</p><form method="dialog"><button type="submit" value="save" data-action="sheet-option">목록에 저장</button><button type="submit" value="share" data-action="sheet-option">공유하기</button><button class="oc-secondary" type="submit" value="cancel">닫기</button></form></dialog></div>`,
  'mobile-form': `<form class="oc-mobile-form"><div><p class="oc-muted">LET’S GET STARTED</p><h2>연락받을 정보를 알려주세요</h2><p>입력 내용은 앱에 연결하기 전까지 전송되지 않습니다.</p></div><div class="oc-mobile-fields">${mobileInput('이름','name','text','name','text','next')}${mobileInput('이메일','email','email','email','email','next')}${mobileInput('연락처','phone','tel','tel','tel','done')}<p class="oc-muted" id="__id__-privacy">예시 폼입니다. 실제 저장 기능은 앱에서 연결하세요.</p></div><div class="oc-mobile-actions"><button type="submit">입력 완료</button></div><p class="oc-feedback" role="status" data-feedback></p></form>`,
  'sticky-action': `<div class="oc-mobile-screen"><div class="oc-mobile-content"><p class="oc-muted">YOUR NEXT PROJECT</p><h2>다음 작업을 시작하세요</h2><div class="oc-mobile-card"><strong>프로젝트 만들기</strong><p>화면을 구성하고 팀과 함께 검토하세요.</p></div><p>버튼은 이 컴포넌트의 스크롤 컨테이너 하단에 머무릅니다.</p></div><div class="oc-mobile-actions oc-action-row"><div><span class="oc-muted">준비되셨나요?</span><strong>새 프로젝트</strong></div><button type="button" data-action="primary">시작하기</button></div></div>`,
  'mobile-list': `<div class="oc-mobile-content"><p class="oc-muted">EXPLORE YOUR WORK</p><h2>이어서 작업하기</h2><ul class="oc-mobile-list"><li><button class="oc-mobile-card" type="button" data-action="mobile-card" data-value="design"><strong>디자인 시스템</strong><span>컴포넌트와 토큰 정리</span><span class="oc-badge">진행 중</span></button></li><li><button class="oc-mobile-card" type="button" data-action="mobile-card" data-value="shop"><strong>모바일 스토어</strong><span>상품 탐색과 주문 흐름</span><span class="oc-badge">검토 중</span></button></li><li><button class="oc-mobile-card" type="button" data-action="mobile-card" data-value="profile"><strong>계정 화면</strong><span>프로필과 알림 설정</span><span class="oc-badge">준비 중</span></button></li></ul><div class="oc-mobile-skeleton" aria-hidden="true"><span></span><span></span><span></span></div><p class="oc-mobile-loading" role="status">목록을 불러오는 중입니다.</p><p role="status" data-mobile-result></p></div>`
};

export const mobileStyles = `
.oc-design[data-mobile=true]{padding:0;overflow-wrap:anywhere;font-size:16px}
.oc-design[data-mobile=true] button{min-width:44px;min-height:48px;touch-action:manipulation}
.oc-design[data-mobile=true] input:not([type=checkbox]){min-height:48px;font-size:16px;scroll-margin-block:16px 120px}
.oc-design .oc-mobile-screen{display:flex;flex-direction:column;min-height:min(600px,calc(100dvh - 2px))}
.oc-design .oc-mobile-content{flex:1;padding:24px 20px}.oc-design .oc-mobile-content>[role=tabpanel]{padding:18px 0}
.oc-design .oc-mobile-tabs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));position:sticky;bottom:0;gap:4px;padding:10px 12px max(12px,var(--oc-safe-bottom,env(safe-area-inset-bottom,0px)));border:0;border-top:1px solid var(--oc-border);background:var(--oc-surface);z-index:1}
.oc-design .oc-mobile-tabs button{display:grid;gap:4px;padding:8px 2px;font-size:13px;border-radius:10px}.oc-design .oc-mobile-tabs button span{font-size:23px;line-height:1.1}
.oc-design dialog.oc-sheet{position:fixed;inset:auto 0 0;margin:0 auto;width:min(100%,480px);max-width:100%;max-height:calc(100dvh - 24px);overflow-y:auto;overscroll-behavior:contain;border-radius:24px 24px 0 0;padding:12px 20px max(20px,var(--oc-safe-bottom,env(safe-area-inset-bottom,0px)))}
.oc-design .oc-sheet-handle{display:block;width:36px;height:4px;background:var(--oc-border);border-radius:4px;margin:0 auto 24px}.oc-design .oc-sheet form{margin-top:24px;gap:12px}.oc-design .oc-secondary{background:var(--oc-background);color:var(--oc-text);border-color:var(--oc-border)}
.oc-design .oc-mobile-form{padding:24px 20px 0;gap:20px}.oc-design .oc-mobile-fields{display:grid;gap:10px}.oc-design .oc-mobile-fields label:not(:first-child){margin-top:8px}
.oc-design .oc-mobile-actions{position:sticky;bottom:0;padding:16px 20px max(16px,var(--oc-safe-bottom,env(safe-area-inset-bottom,0px)));border-top:1px solid var(--oc-border);background:var(--oc-surface);z-index:1}.oc-design .oc-mobile-form .oc-mobile-actions{position:static;margin:0 -20px}.oc-design .oc-mobile-form .oc-feedback:empty{display:none}.oc-design .oc-mobile-actions>button{width:100%}
.oc-design .oc-action-row{display:flex;align-items:center;gap:16px;flex-wrap:wrap}.oc-design .oc-action-row>div{flex:1;min-width:100px}.oc-design .oc-action-row strong{display:block}.oc-design .oc-action-row>button{width:auto;flex:1}
.oc-design .oc-mobile-card{padding:20px;border:1px solid var(--oc-border);background:var(--oc-background);border-radius:var(--oc-radius);text-align:left;color:var(--oc-text)}
.oc-design .oc-mobile-list{list-style:none;display:grid;gap:12px;padding:0}.oc-design .oc-mobile-list button{width:100%;display:grid;gap:8px}.oc-design .oc-mobile-list button>span{font-weight:400}.oc-design .oc-mobile-list .oc-badge{justify-self:start;border:1px solid var(--oc-border)}
.oc-design .oc-mobile-skeleton,.oc-design .oc-mobile-loading{display:none}.oc-design[aria-busy=true] .oc-mobile-list{display:none}.oc-design[aria-busy=true] .oc-mobile-skeleton{display:grid;gap:12px}.oc-design[aria-busy=true] .oc-mobile-loading{display:block}
.oc-design .oc-mobile-skeleton span{display:block;height:126px;background:var(--oc-border);border-radius:var(--oc-radius)}
`;
